Q.1 How many multiplications and additions do you need to perform a matrix multiplication between a (n, k) and (k, m) matrix? Explain.
    Number of mulitplication needed: n*k*m and number of additions needed: n*(k-1)*m
    To calculate every element in the resultant (n,m) array, k multiplications and k-1 additions are required. To fill a row, m such operations are needed; n times to fill the whole array.

Q.2 Write Python code to multiply the above two matrices. Solve using list of lists and then use numpy. Compare the timing of both solutions. Which one is faster? Why?
    The method using a list of lists is faster than the method using numpy. 
    Time for the former method: 0.0008356571197509766s
    Time for the later method: 0.2068006992340088s


In [2]:
import time 
start = time.time()

matrix1 = [[3,1],
           [4,3],
           [4,6]]
# a (n,k) matrix

matrix2 = [[0,4,2],
           [7,4,3]]
# a (k,m) matrix

n = 3 
m = 3
k = 2

out_mat = [[0 for _ in range(m)] for _ in range(n)]

for i in range(n) :
    for j in range(m) :
        for l in range(k):
            out_mat[i][j] += matrix1[i][l] * matrix2[l][j]


print(out_mat)
end = time.time()
print(end-start)

[[7, 16, 9], [21, 28, 17], [42, 40, 26]]
0.0


In [3]:
#using numpy
import numpy as np
import time 
start = time.time()
mat1 = np.array([[3,1],[4,3],[4,6]])
mat2 = np.array([[0,4,2],[7,4,3]])

n = 3 
m = 3
k = 2

out_mat = np.dot(mat1,mat2)
#function to calculate dot product of two arrays
print(out_mat)

end = time.time()
print(end-start)

[[ 7 16  9]
 [21 28 17]
 [42 40 26]]
0.0


Q.3 Finding the highest element in a list requires one pass of the array. Finding the second highest element requires 2 passes of the the array. Using this method, what is the time complexity of finding the median of the array? Can you suggest a better method? Can you implement both these methods in Python and compare against numpy.median routine in terms of time?

In [6]:
#Finding the highest element in a list requires one pass of the array. 
#Finding the second highest element requires 2 passes of the the array.
# Using this method, what is the time complexity of finding the median of the array?

#we'll run a loop till we find  midth highest element 
# where mid = n/2
import time
start = time.time()

num = [1,0,3,4,2,5]
n=6
mid = n//2
ans = 0
for i in range(mid):
    #find highest element
    elem = max(num)
    #for i in num:
    #    if i>elem:
    #        elem = i

    num.remove(elem)
    if n % 2 == 0 and i == mid - 1:
        ans = (elem + max(num)) / 2
    elif n % 2 == 1 and i == mid - 1:
        ans = elem
    n-=1


print(ans)

end = time.time()
print(end-start)
#time complexity O(n^2) n/2 times highest elements and n/2 searches each time

2.5
0.0


In [7]:
#better method
import time
start = time.time()

num = [1,0,3,4,2,5]
n=6
mid = n//2
num.sort()
print((num[mid]+num[mid-1])/2)

end = time.time()
print(end-start)
#time complexity is O(nlogn) as sort() uses quick sort algorithm


2.5
0.0


In [ ]:
#numpy median method
import time
import numpy as np

start = time.time()

num = np.array([1,0,3,4,2,5])
med = np.median(num)
print(med)

end = time.time()
print(end-start)

Q.4 What is the gradient of the following function with respect to x and y? 
$$f(x,y) = x^2*y + y^3*sin(x)$$
    In terms of x:
        $df/dx = (d(x^2)/dx)*y + y^3*(d(sin(x))/dx)$
        $df/dx = 2*x*y + y^3*cos(x)$
    In terms of y:
        $df/dy = x^2*(d(y)/dy) + (d(y^3)/dy)*sinx(x)$
        $df/dy = x^2 + 2*y^2*sinx(x)$